# Generated by Django 5.0.6 on 2024-06-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('dimensions', models.CharField(max_length=100)),
                ('image_hash', models.CharField(max_length=64)),
            ],
        ),
    ]
