# Generated by Django 5.0.6 on 2024-06-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='manufacturer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagedata',
            name='specification',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
