# Generated by Django 5.0.6 on 2024-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imagedata_manufacturer_imagedata_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
